### ISSUE TITLE
Anotar.Serilog.Fody: System.OutOfMemoryException

### ISSUE THREAD

**Issue by vilvm88** [Fody/Anotar#401]
Anotar.Serilog.Fody cause `System.OutOfMemoryException` with double inheritance.

## Code example:

```cs
using Anotar.Serilog;

using Serilog;

namespace AnotarSerilogExceptionSample
{
    interface ILower<T>
    {
        void Foo();
    }

    class Upper<T> : ILower<T>
    {
        public void Foo()
        {
            LogTo.Information("FOO");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .CreateLogger();

            Log.Logger.Information("test");

            new Upper<int>().Foo();
        }
    }
}
```

## Console output

```
[12:50:36 INF] test
Unhandled exception. System.TypeInitializationException: The type initializer for 'AnotarSerilogExceptionSample.Upper`1' threw an exception.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at AnotarSerilogExceptionSample.Upper`1..cctor()
   --- End of inner exception stack trace ---
   at AnotarSerilogExceptionSample.Upper`1.Foo() in C:\Projects\AnotarSerilogExceptionSample\AnotarSerilogExceptionSample\Program.cs:line 16
   at AnotarSerilogExceptionSample.Program.Main(String[] args) in C:\Projects\AnotarSerilogExceptionSample\AnotarSerilogExceptionSample\Program.cs:line 30
```

## Environment

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Anotar.Serilog.Fody" Version="5.1.2" />
        <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    </ItemGroup>

</Project>
```

.net core 3.1.300

## PS

I noticed that in version 5.1.2 logger is generated through `Lazy` class, whereas in 5.1.1 it is not.

```cs
namespace AnotarSerilogExceptionSample
{
	// Token: 0x02000003 RID: 3
	internal class Upper<T> : ILower<T>
	{
		// Token: 0x06000002 RID: 2 RVA: 0x00002050 File Offset: 0x00000250
		public void Foo()
		{
			string text = "FOO";
			object[] propertyValues = Array.Empty<object>();
			string messageTemplate = text;
			if (Upper<T>.LazyAnotarLogger.Value.IsEnabled(LogEventLevel.Information))
			{
				Upper<T>.LazyAnotarLogger.Value.ForContext("MethodName", "Void Foo()", false).ForContext("LineNumber", 16, false).Information(messageTemplate, propertyValues);
			}
		}

		// Token: 0x04000001 RID: 1
		private static Lazy<ILogger> LazyAnotarLogger = new Lazy<ILogger>(new Func<ILogger>(Log.ForContext<Upper<T>>), LazyThreadSafetyMode.PublicationOnly);
	}
}
```

Perhaps this affected this result.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
