### ISSUE TITLE
Log4Net not working

### ISSUE THREAD

**Issue by tpluscode** [Fody/Anotar#61]
Hi. I'm trying to switch from NLog to log4net and it doesn't work. Here's what the error says

```
Error	60	Fody: An unhandled exception occurred:
Exception:
Failed to process 'System.Void MyClass::MyMethod(MyParameter)'.
StackTrace:
   at LogForwardingProcessor.ProcessMethod() in c:\TeamCity\buildAgent\work\b07955b2b87ce7d7\Log4NetFody\LogForwardingProcessor.cs:line 38
   at ModuleWeaver.ProcessType(TypeDefinition type) in c:\TeamCity\buildAgent\work\b07955b2b87ce7d7\Log4NetFody\TypeProcessor.cs:line 50
   at ModuleWeaver.Execute() in c:\TeamCity\buildAgent\work\b07955b2b87ce7d7\Log4NetFody\ModuleWeaver.cs:line 36
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
Source:
Anotar.Log4Net.Fody
TargetSite:
Void ProcessMethod()
Invalid method name
StackTrace:
   at ModuleWeaver.GetLogEnabledForLog(MethodReference methodReference) in c:\TeamCity\buildAgent\work\b07955b2b87ce7d7\Log4NetFody\InjectorExtentions.cs:line 29
   at LogForwardingProcessor.ProcessInstruction(Instruction instruction) in c:\TeamCity\buildAgent\work\b07955b2b87ce7d7\Log4NetFody\LogForwardingProcessor.cs:line 76
   at LogForwardingProcessor.ProcessMethod() in c:\TeamCity\buildAgent\work\b07955b2b87ce7d7\Log4NetFody\LogForwardingProcessor.cs:line 29
Source:
Anotar.Log4Net.Fody
TargetSite:
Mono.Cecil.MethodReference GetLogEnabledForLog(Mono.Cecil.MethodReference)
```

I've tried various combinations of recent Anotar and Fody versions with no change

**Comment by SimonCropp** [comment]
can u upload a repro somewhere. is this in VS 2015?

**Comment by tpluscode** [comment]
Will try. And it's VS 2013

**Comment by tpluscode** [comment]
https://github.com/tpluscode/Anotar.Fody-bug

**Comment by SimonCropp** [comment]
fixed by https://github.com/Fody/Anotar/commit/e9d2542a524c3c4feba074dad89535d73e50532f

**Comment by SimonCropp** [comment]
that was a dodgy palceholder method. there is no Trace in log4net. i will push a new version with that removed.

**Comment by tpluscode** [comment]
That's surprising. It seems that there is no trace method but the trace level actually exists internally. Do you find it worthwhile to implement as suggested in http://stackoverflow.com/questions/1394661/why-isnt-there-a-trace-level-in-log4net?

**Comment by SimonCropp** [comment]
not really. the il is hard coded to support the `ILog` interface https://logging.apache.org/log4net/release/sdk/log4net.ILogMembers.html 

I dont think i want to put more effort into supporting more than 5 levels when even log4net doesnt consider it worth the effort

**Comment by tpluscode** [comment]
Fair enough. And thanks!

**Comment by SimonCropp** [comment]
no worries. and sorry for the hassle
