### ISSUE TITLE
Anotar.CommonLogging.Fody is not compatible with .NET 3.5

### ISSUE THREAD

**Issue by dittodhole** [Fody/Anotar#81]
```
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Sequence contains no matching element
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
1>MSBUILD : error :    at ModuleWeaver.LoadSystemTypes() in C:\projects\anotar\Common\SystemTypesResolver.cs:line 24
1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\anotar\CommonLoggingFody\ModuleWeaver.cs:line 29
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : System.Core
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
```

https://github.com/Fody/Anotar/blob/447582d5d285b67e2e2d9951bdf0f4dba48df9c0/Common/SystemTypesResolver.cs#L24

Any chance on support for .NET 3.5?

**Comment by SimonCropp** [comment]
sorry i dont think i want to put the effort in to support a 9 year old version of .net
