### ISSUE TITLE
Custom logger must implement IsXEnabled

### ISSUE THREAD

**Issue by tpluscode** [Fody/Anotar#83]
The readme says that all listed members of the `Logger` class are optional. However, when calling for example `IsDebug` complains that `IsDebugEnabled` doesn't exist.

If not by design, I'd update the readme file.

**Comment by SimonCropp** [comment]
IsXEnabled should be optional unless you need to use that member. is that not the case?

**Comment by tpluscode** [comment]
See [this gist](https://gist.github.com/tpluscode/83d2065989190fa286ac8f452730aa17)

When `IsDebugEnabled` remains commented out, build fails like so

```
Error		Fody: An unhandled exception occurred:
Exception:
Failed to process 'System.Void IsXEnabledRepro.Program::Main()'.
StackTrace:
   at LogForwardingProcessor.ProcessMethod() in C:\projects\anotar\CustomFody\LogForwardingProcessor.cs:line 38
   at ModuleWeaver.ProcessType(TypeDefinition type) in C:\projects\anotar\CustomFody\TypeProcessor.cs:line 45
   at ModuleWeaver.Execute() in C:\projects\anotar\CustomFody\ModuleWeaver.cs:line 37
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
Anotar.Custom.Fody
TargetSite:
Void ProcessMethod()
Expected to find method 'get_IsDebugEnabled()' on type 'IsXEnabledRepro.Logger'.
StackTrace:
   at CecilExtensions.FindMethod(TypeDefinition typeDefinition, String method, String[] paramTypes) in C:\projects\anotar\Common\CecilExtensions.cs:line 273
   at ModuleWeaver.<>c__DisplayClass38_0.<Init>b__6() in C:\projects\anotar\CustomFody\TypeResolver.cs:line 16
   at Lazy`1.op_Implicit(Lazy`1 d) in C:\projects\anotar\CustomFody\Lazy.cs:line 17
   at ModuleWeaver.GetLogEnabledForLog(MethodReference methodReference) in C:\projects\anotar\CustomFody\InjectorExtensions.cs:line 43
   at LogForwardingProcessor.ProcessInstruction(Instruction instruction) in C:\projects\anotar\CustomFody\LogForwardingProcessor.cs:line 75
   at LogForwardingProcessor.ProcessMethod() in C:\projects\anotar\CustomFody\LogForwardingProcessor.cs:line 29
Source:
Anotar.Custom.Fody
TargetSite:
Mono.Cecil.MethodDefinition FindMethod(Mono.Cecil.TypeDefinition, System.String, System.String[])	IsXEnabledRepro			
```

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
